language: node_js

services:
  - mysql
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE ohmyform;'
  - psql -c 'create database ohmyform;' -U root

env:
  global:
    - CREATE_ADMIN=true
    - ADMIN_EMAIL=admin@localhost
    - ADMIN_USERNAME=admin
    - ADMIN_PASSWORD=admin
    - MAILER_URI=smtp://localhost:1025
  jobs:
    - DATABASE_DRIVER=mariadb DATABASE_URL=mysql://root@127.0.0.1:3306/ohmyform
    - DATABASE_DRIVER=postgres DATABASE_URL=postgresql://root@127.0.0.1:5432/ohmyform
    - DATABASE_DRIVER=sqlite DATABASE_URL=sqlite://

node_js:
  - 16
  #- 14
  #- 12

cache:
  yarn: true

install:
  #- rm yarn.lock
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn typeorm migration:run
